baseURL: "https://www.larstendolle.com"
languageCode: en-us
title: Lars ten Dolle
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "I'm Lars &#x1F44B;"
    subtitle: "Welcome to my blog!"
    buttons:
      - name: About
        url: "/about/"

  
  ShowShareButtons: true
  
  ShowPostNavLinks: false

menu:
  main:

  - identifier: categories
    name: Categories
    url: /categories/
    weight: 10
  - identifier: archives
    name: Archives
    url: /blog/
    weight: 20
  
  



