baseURL: "https://www.larstendolle.com"
languageCode: en-us
title: Lars ten Dolle
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "I'm Lars"
    subtitle: "Welcome to my blog!"
    buttons:
      - name: About
        url: "/about/"
      - name: Contact
        url: "/contact"
      
  


  
  ShowShareButtons: true
  
  ShowPostNavLinks: false

menu:
  main:

  - identifier: archives
    name: Archives
    url: /blog/
    weight: 10
  
  



