baseURL: "https://www.larstendolle.com"
languageCode: en-us
title: Lars ten Dolle
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "I'm Lars! &#x1F44B;"
    subtitle: "Welcome to my blog!"
    buttons:
      - name: About
        url: "/about/"
      - name: Blog
        url: "/blog/"

