baseURL: "https://www.larstendolle.com"
languageCode: en-us
title: Lars ten Dolle
theme: PaperMod

params:
  profileMode:
    enabled: true
    title: "I'm Lars! &#x1F44B;"
    subtitle: "Welcome to my blog!"
    buttons:
      - name: About
        url: "/about/"
      - name: Blog
        url: "/blog/"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]