baseURL: "https://www.larstendolle.com"
languageCode: en-us
title: Lars ten Dolle
theme: PaperMod

params:
    homeInfoParams:
        Title: "I'm Lars! &#x1F44B;"
        Content: "Welcome to my blog!"



      
      
  


  
  ShowShareButtons: true
  
  ShowPostNavLinks: false

